### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by 3pleo** [dotswan/filament-laravel-pulse#1]
Thanks for a great plugin.
Please update the installation guide to include users have to install Pulse first.
`composer require laravel/pulse`
`php artisan vendor:publish --provider="Laravel\Pulse\PulseServiceProvider"`
`php artisan migrate --step`

**Comment by mohaphez** [comment]
Hi @3pleo 

Thank you for your feedback and for appreciating the plugin.

The installation guide has been updated.
