### ISSUE TITLE
Dark mode on Dashboard

### ISSUE THREAD

**Issue by OverboredThekid** [dotswan/filament-laravel-pulse#2]
I am running into an issue where some of the fields on the dashboard aren't using dark:bg- when Filamentphp dark mode is enabled

<img width="1163" alt="Screenshot 2024-07-23 at 1 19 17 AM" src="https://github.com/user-attachments/assets/e29d19da-d23c-478a-b9a8-d74156b8ce8f">

**Comment by Sirajunnasihin** [comment]
Add this `'./vendor/laravel/pulse/resources/views/**/*.blade.php',` to `tailwind.config.js`

example :
`import preset from './vendor/filament/support/tailwind.config.preset'

export default {
    presets: [preset],
    content: [
        // Add here
        ./vendor/laravel/pulse/resources/views/**/*.blade.php',
    ],
}
`

**Comment by OverboredThekid** [comment]
that worked, thank you!
