### ISSUE TITLE
Add @tailwindcss/container-queries

### ISSUE THREAD

**Issue by kiwina** [dotswan/filament-laravel-pulse#4]
Not a big one but pulse make use of the @tailwindcss/container-queries plugin adding it may be a good idea

Add to your packages
```
"@tailwindcss/container-queries": "^0.1.1",
```
update the custom theme tailwind.config.js
```
import container from '@tailwindcss/container-queries'
export default {
    presets: [preset],
    content: [
       // ...
        './vendor/laravel/pulse/resources/views/**/*.blade.php',
    ],
    plugins: [container],
}
```

**Comment by mohaphez** [comment]
Hi @kiwina  
Now in new version we handle it 
Thank you for your advice
