### ISSUE TITLE
Filter for Duration not working properly

### ISSUE THREAD

**Issue by ademiawansyah** [dotswan/filament-laravel-pulse#8]
I've successfully create pulse dashboard using this filament plugin. 
But when i'm trying to Filter duration, it's not working. 
![image](https://github.com/user-attachments/assets/cc276b75-5c82-40b2-ad44-50de301d2645)

It got error no route define
![image](https://github.com/user-attachments/assets/7f3edcce-c387-42e1-82f4-e15d68158202)

Here's the source code of the custom pages and AdminPanelProvider
Location `app\Filament\Pages\SystemDashboard.php`
![image](https://github.com/user-attachments/assets/75893ec8-5bf3-4558-91b3-38a3ecf6a7ec)

AdminPaneProvider:
![image](https://github.com/user-attachments/assets/e5fba4f9-7b76-46e9-95fa-a68c5e13f5b4)

**Comment by mohaphez** [comment]
Hi @ademiawansyah,

Please check the list of routes using `php artisan route:list`. You should be able to find the correct route name for this page.

If the issue persists or if you encounter any other problems, feel free to let us know. We're here to help!
